name: Package Project
run-name: ${{ github.actor }} is packaging the project
on:
  # This event should allow for manual workflow triggering
  workflow_dispatch:
  # Run on push to main branch
  push:
    branches:
      - main
  # Runs every time a pull request is created or updated
  pull_request:
concurrency:
  # Define concurrency group name which will then be used to determine duplicate workflow runs
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  package-project:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          architecture: x64
          # Cache maven dependencies for quicker runs
          cache: maven
      - name: Package the Project
        run: mvn package
      - name: Upload an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-project
          path: target/wls-*.jar
          if-no-files-found: error
          overwrite: true
